Repository heroku/sf-functions-python, pull requests merged in 2022-12, with the labels that each got.

#30 Add README badges for PyPI and CI
  README.md
Labels: skip changelog

#32 Add integration testing in CI using the CNB and Salesforce CLI
  .github/workflows/ci.yml
  tests/fixtures/template/main.py
  tests/fixtures/template/project.toml
  tests/test_app.py
  tests/test_function_loader.py
Labels: skip changelog

#33 Enable the pylint `useless-suppression` rule
  pyproject.toml
Labels: skip changelog

#29 Add getting started documentation
  README.md
  assets/developer-console.png
Labels: skip changelog

#35 Improve cleanup of the custom `sys.tracebacklimit` in tests
  tests/test_app.py
  tests/test_cli.py
Labels: skip changelog

#37 Refactor the internal CLI/ASGI app API for project path
  salesforce_functions/_internal/app.py
  salesforce_functions/_internal/cli.py
  salesforce_functions/_internal/config.py
  tests/test_app.py
  tests/test_cli.py
  tests/test_config.py
  tests/utils.py
Labels: skip changelog

#38 Switch to using the Salesforce REST API version from `project.toml`
  CHANGELOG.md
  pyproject.toml
  salesforce_functions/_internal/app.py
  salesforce_functions/_internal/cli.py
  salesforce_functions/_internal/config.py
  tests/fixtures/basic/project.toml
  tests/fixtures/data_api/project.toml
  tests/fixtures/invalid_missing_main_py/project.toml
  tests/fixtures/logging/project.toml
  tests/fixtures/project_toml_api_version_at_minimum/project.toml
  tests/fixtures/project_toml_api_version_invalid/project.toml
  tests/fixtures/project_toml_api_version_missing/project.toml
  tests/fixtures/project_toml_api_version_too_old/project.toml
  tests/fixtures/project_toml_api_version_triple_digits/project.toml
  tests/fixtures/project_toml_api_version_wrong_type/project.toml
  tests/fixtures/project_toml_file_missing/.gitkeep
  tests/fixtures/project_toml_invalid_toml/project.toml
  tests/fixtures/project_toml_invalid_unicode/project.toml
  tests/fixtures/project_toml_salesforce_table_missing/project.toml
  tests/fixtures/project_toml_salesforce_table_wrong_type/project.toml
  tests/fixtures/raises_exception_at_runtime/project.toml
  tests/fixtures/return_value_not_serializable/project.toml
  tests/fixtures/returns_context/project.toml
  tests/fixtures/returns_event/project.toml
  tests/test_app.py
  tests/test_cli.py
  tests/test_config.py
Labels: enhancement, breaking change

#42 Use coverage-conditional-plugin to reduce `no cover` annotations
  pyproject.toml
  salesforce_functions/_internal/cloud_event.py
  salesforce_functions/_internal/config.py
Labels: skip changelog

#43 Add a test for DataAPI's shared session handling
  salesforce_functions/data_api/__init__.py
  tests/test_data_api.py
Labels: skip changelog

#39 Update getting started documentation to use the stable CLI release
  README.md
Labels: skip changelog

#45 Update README to align with Salesforce style & tone guidelines
  README.md
Labels: documentation, skip changelog

#47 Add a README badge for supported Python versions
  README.md
Labels: documentation, skip changelog
